# Generated by Django 5.1.5 on 2025-01-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='is_hourly',
            field=models.BooleanField(default=False, help_text='Set to True for hourly bookings.'),
        ),
    ]
