# Generated by Django 5.1.5 on 2025-01-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_adminapp', '0002_bookingroom_is_hourly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingRoom',
        ),
    ]
