# Generated by Django 5.1.5 on 2025-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_adminapp', '0004_rooms_clining_fees_rooms_gst_rooms_room_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelroomtype',
            name='room_type',
            field=models.CharField(blank=True, choices=[('luxury', 'Luxury'), ('executive', 'Executive'), ('premium', 'Premium')], max_length=100, null=True),
        ),
    ]
