# Generated by Django 5.1.5 on 2025-01-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_adminapp', '0005_alter_hotelroomtype_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='check_out',
        ),
    ]
